#14 add draggable
KoheiB/cipher_application pull request #15
Opened 2021-01-04 15:20 UTC by KoheiB

カードを動かしたら同じ種類のカードが追従する機能をつくりました。
一応それっぽくできたと思ってますが、本家の動きをあまり覚えてないので動作確認までお願いしたいです。
コードが繰り返しになってるのは後々リファクタリングします。

2021-01-06 06:42 UTC, henry11239987 commented on components/CardPicked.vue
> +<template>
ファイル名ですが、PickedCardのほうがいいかな～と思います。
デッキに採用されている（Pickされている）カード、という意味合いですよね？
CardPickedだと、動詞みたいに見えて混乱します。

2021-01-06 06:44 UTC, henry11239987 commented on pages/buildDeck.vue
> +            <CardPicked
コンポーネント名について同上です。

2021-01-06 07:28 UTC, henry11239987 commented on pages/buildDeck.vue
> +    // 1枚のカードをドラッグした際、同じ種類のカードの順序をまとめて入れ替えるためのメソッド
処理の内容は理解できたんですが、もとのコメントだけだと見返したときに意味わからなくなりそうと思いコメントを足しました。
認識違い、よりよい表現などあれば適宜追加で修正お願いします。

2021-01-06 07:35 UTC, henry11239987 requested changes
挙動とコード確認しました。
挙動は一旦OKだと思います。

コードについては、下記2点を改めて対応お願いします。
・私が追加したコメントに認識違いがないかを確認
・私が追加したコメントの表現で理解できるか確認、適宜修正
・共通処理部分のリファクタリング

2021-01-08 16:54 UTC, KoheiB commented
- コンポーネント名を変更

- 関数の共通処理部分をリファクタリング
ネスト内に関数を書くなとESLintに怒られたので、普通にNuxtのmethodsに記載することにしました。

- コメントを適宜修正（大筋は変わらず）

2021-01-10 08:56 UTC, henry11239987 requested changes
一度目のレビュー時に、レビューしたという判定になってなさそうだったので遅ればせながらやりました。

2021-01-10 11:08 UTC, henry11239987 approved these changes
コードレビュー、動作の再確認まで完了しました。
追加指摘ありません。マージしちゃいます。

2021-01-10 11:08 UTC, merged