add data model prototype
KoheiB/cipher_application pull request #16
Opened 2021-01-06 15:20 UTC by henry11239987

ざっくりデータモデル作りました。
マークダウン形式のほうがfirestoreの構造そのまま表せて楽だったのでこちらにしました。
スプレッドシートの仕様には一通り目を通して、必要そうなものを一通り書いたつもりです。

・これどういう意味？
・これ足らなくね？
みたいなのあったら指摘お願いします。

一旦これで作り始めてみて、実装上不都合があったら構造を直すという流れが現状一番現実的かなと思ってます。

2021-01-06 15:32 UTC, henry11239987 commented
imageRefの件については検討したんですけど、万が一画像の格納先を移動するとなった場合、既存のDecksおよびCardsのimageRefを全部更新することになっちゃうなあというのが懸念点でして。

CardIdについてはまず変更がないからKeyIDとして用いてよいとして、imageRefについてはやはり生成するメソッドをフロント側で別途用意したほうが良いと思います。（これだと、格納場所変わってもメソッドいじるだけで済むはず）

2021-01-06 16:46 UTC, KoheiB requested changes

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +        - password  : string <!-- 認証回りをfirestore authenticationに任すならこれ要らない？ -->
認証周りはFireauthで一元管理するのがセキュリティ的にも楽なので、Firestore上にpasswordは必要ないです。

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +- Cards : collectioon <!-- 一旦は検索条件に必要な最低限のカラムでいいのではという想定 -->
カラムはおそらくFirestoreでいうFieldですよね。
僕もいったんはその考えです！
あと、staticとassetの使い方の違いってわかりますか？
調べたんですがしっくりきてません。

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +        - updatedAt : timestamp
CardsのcreatedAt, updatedAtは必要ありますか？

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +        - markedOtherPlayersDecks : string
> markedOtherPlayersDecks : string

すみません、これが何か分からないので説明お願いします。

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +        - Decks : collectionGroup
> collectionGroup

デッキ一覧を取得する際にコレクショングループメソッドを使用するという意味合いですか？

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +                - posting? : boolean
```suggestion
                - isPosted : boolean
```

？はFirestoreだと馴染みがないのでおそらくこちらの表記になります。
publicについても同様です。

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +                - comment : string
実装の優先度は低いですが、いいね数を追加しておきましょうか。

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +                - mainClassCangeCard : string
```suggestion
                - mainClassChangeCard : string
```

2021-01-06 16:46 UTC, KoheiB commented on store/data.md
> +                - public? : boolean
```suggestion
                - isPublic : boolean
```

2021-01-07 00:25 UTC, henry11239987 commented on store/data.md
> +        - password  : string <!-- 認証回りをfirestore authenticationに任すならこれ要らない？ -->
了解です

2021-01-07 00:54 UTC, henry11239987 commented on store/data.md
> +- Cards : collectioon <!-- 一旦は検索条件に必要な最低限のカラムでいいのではという想定 -->
すみません、フィールドですね。

staticとassetsについては自分も気になってました。
下記ページの説明を見る感じ、３に該当するのでstaticでよいのかなという印象です。
https://daigaku.university/archives/1027
・png, jpeg, gifなど画像ファイル
１．通常ページ内で使う場合はassets
２．OGPやfavicon.icoなど外部から読み込む可能性のものはstatic
３．その他、ファイル名が変わってまずいものはstatic（assetsだとwebpackがファイル名を変える可能性が高いので）

2021-01-07 00:54 UTC, henry11239987 commented on store/data.md
> +        - updatedAt : timestamp
確かに要らないですね、消します。

2021-01-07 00:57 UTC, henry11239987 commented on store/data.md
> +        - markedOtherPlayersDecks : string
いいねをした他プレイヤーのデッキID一覧という意味合いでした（stringじゃなくてarray[string]ですね、すみません）

いいね周りのデータの持ち方がいまいち想像つかず、一旦ここに持たせてみた次第です。

画面上で「自分がいいねしたデッキ一覧」とか表示するときに、ここを参照すれば一発みたいなイメージで用意しました。

2021-01-07 01:09 UTC, henry11239987 commented on store/data.md
> +        - Decks : collectionGroup
その意味合いです。
改めて調べてみるとcollectionGroupは型の名前じゃないですね。

ここに記載されているべき文言は「collection」あるいは「subcollection」が適切でした。「subcollection」に変更します。

2021-01-07 01:09 UTC, henry11239987 commented on store/data.md
> +                - posting? : boolean
了解です

2021-01-07 01:11 UTC, henry11239987 commented on store/data.md
> +                - comment : string
いいね「された」数、ですね。
了解です。

2021-01-07 01:24 UTC, KoheiB commented on store/data.md
> +        - markedOtherPlayersDecks : string
了解です、それだとユーザーのサブコレを配置するのが良いです。
あとデッキにデッキをいいねしたユーザー一覧のサブコレももたせる必要があります。
後ほど参考URLを共有しますが取り急ぎ。

2021-01-07 01:25 UTC, KoheiB commented on store/data.md
> +                - comment : string
そうですね、likedCountとかで良いかと。

2021-01-07 05:58 UTC, henry11239987 commented
いただいたURLを参考にして、大きく修正を加えました。

下記2点について改めて確認をお願いします。
・いいね周りのデータについて、このもちかたでいいか
・デッキ側が持つのカード情報について、リストとサブコレのどちらがいいか（実装難易度的に。サブコレのほうがクライアントジョインしなくて済むから楽なんじゃないかなと思ってます）

2021-01-07 10:47 UTC, KoheiB requested changes
サイト貼っただけで全部理解しててさすがの一言です！
レビューしましたのでご確認お願いします。
また、ShareにFirestoreの記事を追加しました。
主にFirestoreからデータを引っ張るときのやり方が書いてありますので、設計の参考にしてみてください！

2021-01-07 10:47 UTC, KoheiB commented on store/data.md
> +- Users : Collection
### 【命名について】

- コレクションの名前がアッパーキャメルケースになっていますが、いいねのサイトの筆者がたまたま採用しているだけで、通例というわけではないです。（公式ドキュメントはキャメルケース（非アッパー））
このプロジェクトではアッパーキャメルケースを採用するということで統一するならそれもありだと思いますが、どう思いますか？

- 全体でmarkedからmarkになってますが、markedの方が意味的には合っている気がしますがどうですか？

- DocumentIDにdeckIdなどが記載されていますが、FirestoreではドキュメントIDにキー名とかは設定できません。（RDBだとできる？そちらについて僕が無知なのでわかりませんが・・・）
- DocumentIDはFirestoreが生成するランダムな文字列か指定の文字列を指定できますので、どちらの手法でドキュメントを作成・追加していくか、書くといいと思います。（例　deckID：DocumentID：random　または何を指定してドキュメント作成するか書く。）
別のドキュメントのID文字列を持たせてリレーションを作ったりできますので、それぞれ考えてみてください。よろしくお願いします！

2021-01-07 10:47 UTC, KoheiB commented on store/data.md
> +                -->
- リストで持たせるとドキュメントが煩雑化する＋非正規化（二重持ち）でreadのコストを抑えられることから、サブコレクション案を採用しましょう！
また、カードIDを別途非正規化して持たせてください。
並べるだけならIDしか使用しませんが、readコストを抑えて主人公カードの指定や、採用されているシンボルの割合を取得して表示できたりするのでいろいろできることが広がりそうでいいですね。

- また、コレクション名について、CardsInDeckとInDeckCardsはどちらが一般的ですか？

- createdAtは必要ですか？

2021-01-07 10:47 UTC, KoheiB commented on store/data.md
> +                -->
こちらも非正規化案でいきましょう

2021-01-07 10:47 UTC, KoheiB commented on store/data.md
> +                - isPublic : Boolean
こちらもサブコレクション＋非正規化しましょう

2021-01-07 10:47 UTC, KoheiB commented on store/data.md
> +                - isPosting : Boolean
isPostedよりisPostingの方が良さそうですか？

2021-01-07 10:47 UTC, KoheiB commented on store/data.md
> +                    - updatedAt : Timestamp
updatedAtは不要かと思います。

2021-01-07 10:47 UTC, KoheiB commented on store/data.md
> +            - updatedAt : Timestamp
こちらもupdatedAtは不要かと！

2021-01-07 12:02 UTC, henry11239987 commented on store/data.md
> +- Users : Collection
上記のコメントそれぞれに上から１，２，３，４と番号が振ってある想定で回答します。（コピペしてインラインだとめちゃくちゃ長いので。。。）

1. 私個人の中でなんとなく規則決めて書いてましたが、命名規則はどこかで明示したほうがいいですね。失礼しました。スプレッドシートに記載しておきます。
一旦は下記で考えてます。
コレクション名：アッパーキャメルケース
それ以外　　　：ローワーキャメルケース

2. （デッキ、ユーザが）markした、という意味合いでは？と思ったのでedを外した次第です。元の命名だと「～された」という受動のed（例：favorited）と、「～した」という過去形のed（例：marked）が混在してしまっていたという認識です。なので、設計全体でedは受動だけにする方針で直しました。

3. 4. 指摘ありがとうございます、こちらの書き方が悪かったですね。DocumentIDに名前（コレクション名、フィールド名みたいな）をつけられないのは認識しています。おっしゃるとおり今はrandomでいいものと明示的に別コレクションのIDと一致させて紐付けるものが混在してるので、例で示していただいた形で追記します。

2021-01-07 12:14 UTC, henry11239987 commented on store/data.md
> +                -->
1. 非正規化の方針で了解です。カードIDについては、CardsのDocumentIDとInDeckCardのDocumentIDを一致させる想定でした。この場合でもInDeckCardのフィールドにカードID必要でしょうか？

2.  微妙ですね。なんならDeckCardでいいのでは？という気がしてきました。

3. 投入した順という意味で必要ではないでしょうか。リストじゃなくなったので、このcreatedAtがないと順番を保持出来ないかなと思いました。（createdAtの昇順とかでデータ取得すると自ずと画面表示順になるイメージでした。）
ただ、よくよく考えるとcreatedAtに入るTimestampの精度によっては表示順を担保できないかもしれないですね。。。（ミリ秒以下まで完全一致されると。。。）フィールドに表示順の番号をもたせる形なら確実なので、こちらに変更する方針で良いでしょうか？
更にいうと、採用枚数をフィールドに持ったほうがいいですね。追加しておきます。

2021-01-07 12:17 UTC, henry11239987 commented on store/data.md
> +                - isPosting : Boolean
isPostedのほうが自然ですね。そっちにします。

2021-01-07 12:18 UTC, henry11239987 commented on store/data.md
> +                    - updatedAt : Timestamp
確かにRefで持つならアプデしないですね。消しときます。

2021-01-07 12:20 UTC, henry11239987 commented
レビューありがとうございます！褒められてめちゃくちゃ嬉しい嬉しい。

いくつか頂いた指摘に回答したので確認お願いします。
また、コメントするほどじゃないものにはGoodスタンプ投げたので確認次第「Resolve conversation」で閉じちゃってください。

2021-01-07 13:59 UTC, KoheiB requested changes

2021-01-07 13:59 UTC, KoheiB commented on store/data.md
> +                -->
1. 一応オタクの同人誌でその場合でもカードIDを持たせた方がいいとのことです。（簡潔にデータを取得できるため。）
2. DeckCardsはさすがにわけわからんくないですか？先の２択でどっちかでいいと思います。
3.createdAtだとびみょうですね、orderを持たせる形ですかね。あれ、なんか微妙になってきたな・・・配列でカードIDをリストで持たせるのだと表示するだけなら楽なんですよね。
やっぱりクライアントサイドジョインにします？
ちょっとこれ今度通話で話したいかもです。

2021-01-07 13:59 UTC, KoheiB commented on store/data.md
> +                - isPublic : Boolean
CardsInDeckと同じ仕様。

2021-01-08 02:50 UTC, henry11239987 commented on store/data.md
> +                -->
りょです

先の２択がいまいちどっちもしっくりきてないんですよね。。。少なくともCardsInDeckは馴染みがないです。UseCardsとかContainCardsとか動詞＋名詞の形にします？

通話しましょう。一旦orderとcount足したサブコレを有効にしてコミットしますね。（リストはコメントアウトで残しときます。）

2021-01-09 07:56 UTC, henry11239987 commented
昨日会話した件含めて修正しました。
これで一旦進められると思うので問題なければマージまでお願いします。

Cardsのフィールドなんですが、データインポートのタスクに着手してみたら、一旦は要らないフィールドも簡単にインポートできたんでモデルにも反映しました。（後で必要になったときに入れ直すというのも面倒なので）
実装時には必要なフィールドだけ参照してください。

2021-01-09 08:00 UTC, henry11239987 commented on store/data.md
> +- Cards : collectioon <!-- 一旦は検索条件に必要な最低限のカラムでいいのではという想定 -->
別イシューに切り分けました。

2021-01-11 05:20 UTC, merged