[WIP]#23 search card list
KoheiB/cipher_application pull request #25
Opened 2021-01-22 12:31 UTC by KoheiB

作成途中につき、レビューは不要です。
デッキ作成画面が少し変わっています。
よければご確認ください。

- [ ] カード一覧からデータ取得

- [ ] 無限スクロール導入

- [ ] オートコンプリート途中まで

2021-01-22 12:32 UTC, KoheiB commented
#21 のコミットが入ってしまっている。。。
ミスです、気にしないでください。

2021-01-26 12:05 UTC, KoheiB commented
@henry11239987 
ひとまずカード検索機能について一通り実装完了しましたので、レビューお願いします。

### レビューに際して
- UXに関しては、自分視点だと甘くなってしまうと思っているので、ここはこうした方が使いやすいなどは厳しめに指摘して欲しいです。
- 検索の挙動の確認は割と念入りに行いましたが、ぶるそーさんの方でも変な動きがないかよく確認をお願いします。

### 検討中の事項
- Search、Bookmarkといったタブ名の名称（ボタン名を何にしようか考えてたら、キープがいい感じかもと思った）
- 検索結果リストの高さどうやって設定しよう問題（グルグル部分が見える程度に画面いっぱいに広げたい）
- フィルター周りのメソッドが力技なので、リファクタリングしたい
- その他、ブックマーク機能、カード追加機能についてはとりあえず簡単なレイアウトのみの実装なので、別Issueで対応予定です。レイアウトに関して意見等ありましたらお願いします

2021-01-27 05:18 UTC, KoheiB commented
@henry11239987 （補足）検討中の事項のリファクタリングについては、後日別Issueでやります！やってくださいと言ってるようにも読めるかなと思ったので補足。

2021-02-03 11:08 UTC, KoheiB commented
@henry11239987 
[バグ報告]
検索ドロワーで下の方の追加データを読み込んでからキャラ名でフィルターし直すと、二重に表示されることがある。
アサマやアズールで確認、アウグストやアランなど一画面に収まるキャラでは確認できない。
この辺りにヒントがありそうですが、原因は調査中です。

この件については別Issueで対応するつもりですが、もし原因がわかったらご教示ください。

2021-02-06 08:33 UTC, henry11239987 commented on pages/buildDeck.vue
> +          prepend-inner-icon="mdi-database-search"
アイコンについて、database-searchかと言われるとちょっと違和感あります。
ユニットを表す人形シルエットが使われているアイコンとかで再検討いただけないでしょうか。

2021-02-06 08:34 UTC, henry11239987 commented on pages/buildDeck.vue
> +          <v-list class="py-0 overflow-y-auto" height="450" outlined>
heightが450なのは意図がありますか？

2021-02-06 08:37 UTC, henry11239987 commented on pages/buildDeck.vue
> +      // UIコンポーネント
コメントですが、かかっている対象がおそらく直下1行ではなく複数行にかかっているんですよね？
そういう意味なら、下記のように改行入れてグループをわかりやすくして、「〇〇関連」的なコメントにしたほうが良いと思いました。
```
      filteredCards: [],

      // UIコンポーネント関連
      drawer: null,
      tab: null,

      // ページネーション関連
      nextFilteredCards: null,
      lastFilteredCard: null,

      // ユニット名フィルター関連
      unitNameFilter: undefined,
```

2021-02-06 08:38 UTC, henry11239987 commented on pages/buildDeck.vue
> +              <span slot="no-more">No More Cards</span>
「No More Cards」って表示必要ですかね。
スクロールしてそれ以上出てこなければ、直感的に以上であることはわかりそうなものだなと思いました。

2021-02-06 08:39 UTC, henry11239987 commented on pages/buildDeck.vue
> +              <span slot="no-results">No More Cards</span>
引っかからなかった場合という意味では、「No More Cards」ではなく「Not exist」とかのほうが良いかなと思いました。

2021-02-06 08:40 UTC, henry11239987 commented on pages/buildDeck.vue
> +      symbolFilterItems: [
定数にしたほうがよいと思います。
機能増やしていくとどこかで使うかもしれません。

2021-02-06 08:42 UTC, henry11239987 commented on pages/buildDeck.vue
> +    async changeFilter() {
メソッド名、厳密に言えば「change'd'」かなと思いました。
メソッドが「change」するのではなくて、ユーザによって「change」されたときに動くメソッドなので。

あと、メソッド名と全く同じ意味のコメントは不要です。

2021-02-06 08:43 UTC, henry11239987 commented on pages/buildDeck.vue
> +    // フィルターをリセット
コメント不要かと。メソッド名通りなので。

2021-02-06 08:44 UTC, henry11239987 commented on pages/buildDeck.vue
> +        const imageUrl = '/img/' + card.recording + '/' + newId + '.png'
imageUrl生成メソッドとして共通化しましょう。
色んな所で使うと思うので。

2021-02-06 08:45 UTC, henry11239987 commented on pages/buildDeck.vue
> +    addSymbolColorData(symbols, data) {
- ベタ書きなのが気になります。
        - 修正案
            - L256の「symbolFilterItems」をオブジェクト型にして、背景色情報も合わせてもたせる。
            - L451でシンボル名と背景色をまとめて設定。
            - 「addSymbolColorData」メソッドにかけて、ダブルシンボルなら背景色情報を上書きする。
        - これだとL472~L501までバッサリ削れるかと。

2021-02-06 08:46 UTC, henry11239987 commented on pages/buildDeck.vue
> +        if (this.nextFilteredCards.size <= 9) {
コメントが「10未満」なので、「< 10」のほうが統一感あっていいかと。

2021-02-06 08:54 UTC, henry11239987 requested changes
実装お疲れさまです。また、確認遅れてすみません。
レベル高くてめちゃ勉強になります。

挙動について、特にバグっぽい動きはなかったです。
報告いただいている件もちょっとこちらだと再現せず、後日改めて確認させてください。

コードレビュー内容はコメントで追加しました。
確認お願いします。

また、コード以外の部分で気になったものを羅列します。
- UX周り
    - ユニット情報ですが、文字が薄くて少し見にくいかなと思いました。ただ、vuetifyのデフォルト使ってるだけっぽいので無理に変えなくてもいいかという気もしています。
    - フォントについて、現時点でも特段不満という程ではないですが、余裕あれば変えることも検討しても良いかもしれません。（多分アプリ全体に波及する話なので、優先度は低めと思っています。）
    - 枚数追加の見た目、左から「-ボタン」・「今デッキに採用されている枚数が表示されるテキストボックス」・「＋ボタン」的な形になっていると良いかなと思います。今の見た目だと枚数減らす手段がないので。。。
    - ブックマーク機能のタブとボタン名ですが、「KEEP」で賛成です。ブックマークもボタン名も「KEEP」の英字表記で統一したほうが良いと思いました。



- 機能周り
    - オートコンプリート機能ですが、個人的にイメージしていたものとすこし違って違和感を覚えました。「て」と打ち始めたら頭文字が「て」のものに絞られるイメージでしたが、今は「て」を含むものがすべて出てきてしまうみたいですね。頭文字で絞り込むようにすることって可能でしょうか。。。？L533の「filterObject」メソッドで「includes」使っているのが問題？
    - 現「BOOKMARK」タブを開いているときに検索フィルターの中身を変えた場合、「SEARCH」タブに自動で切り替わってくれると嬉しいです。
    - 現状の検索項目だと、1ユニットで収録数がめちゃくちゃ多いやつ（アイクとか）を探す場合にちょっと面倒くさいパターンがあると思いました。
        - 例えば22弾アイクの上下だけ探すとなったとき、かなりのスクロールと追加読み込みが必要になります。他にも、PRマルス探すとかもだいぶだるいですね。
        - 検索項目を増やすか、昇順降順切り替えを追加するとかで改善できないでしょうか。

2021-02-06 11:28 UTC, KoheiB reviewed
レビューありがとうございます！
こちらこそかなり大規模なプルリクになってしまい申し訳ないです。
もうちょいこまめにレビュー頼んだほうがいいですかね？どうなんだろう。

ところどころ疑問とかもあるので、詳細は明日共有して相談したいです。
あとこのブランチから派生して別作業進めてしまっててて、その際に思いつきで修正したりしている箇所とかもあるので、指摘いただいたTODOは別Issueでまとめておきますので、取り急ぎMergeをお願いしたいです。
ごちゃごちゃしててすみません、よろしくおねがいします。

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +    async changeFilter() {
メンターに相談しました。
@changeで発火するメソッドなので、そもそもonChangeのようなのは二重の意味になるのでよろしくないとのことです。
頭痛が痛い的な感じで。
フィルターが変わったら何が起きるか、を書くべきだそうなので、filterCardsとかがいいかもしれないです。
cardって単語がいっぱい出てきて非常に分かりづらくて悩みどころ。。。
一通り実装した後にどこかで統一しなければと思ってはいますが。。。
別Issue立てます。

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +              <span slot="no-results">No More Cards</span>
なんか挙動が変になるから同じにしちゃったんですよね
カード出てるのにNo Existsが出るみたいな、苦肉の策でとりあえずって感じです。
明日ガチャガチャして共有します。
別Issue立てます。

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +              <span slot="no-more">No More Cards</span>
一応入れておきましたが、おっしゃるとおりです。
下記の検索してなかった場合と含めて、何も表示しなくてもいいかもしれないですね。

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +          prepend-inner-icon="mdi-database-search"
修正しました！
シンボルもそれっぽいアイコンがあったらいいんですけど、あまり思いつかないですね。。。

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +          <v-list class="py-0 overflow-y-auto" height="450" outlined>
仮の数字でした、修正しましたが、これも微妙なので他Issue立てておきます。

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +      symbolFilterItems: [
OKです。別Issueで立てます！

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +        const imageUrl = '/img/' + card.recording + '/' + newId + '.png'
OKです。
別Issue立てます。

2021-02-06 11:28 UTC, KoheiB commented on pages/buildDeck.vue
> +    addSymbolColorData(symbols, data) {
シンボルフィルター周りの別Issueに統合します！
背景色についてはひとつ考えてるデザインがあり、その実装方法次第で変わる可能性があるので保留で！

2021-02-06 11:32 UTC, merged

2021-02-06 11:34 UTC, henry11239987 commented
派生して別作業やってる旨承知です。
取り急ぎマージしました。