#28_add unitNames, fix Cards data
KoheiB/cipher_application pull request #30
Opened 2021-01-24 08:43 UTC by henry11239987

重複を除いたユニット名の定数を用意しました。

持ち方は[こちら](https://qiita.com/amagurix/items/0f19d04b7771a71b5eaf)を参考にしています。利用方法もあわせて確認お願いします。

また、この作業の折に一部Cardsデータが正しく設定されていないことを確認したので、合わせて修正しました。
誤っていたもの

例）
- 正：織部 つばさ
- 誤：つばさ

原因：スクレイピング実行時、区切り位置にミスがあった。

2021-01-24 10:39 UTC, KoheiB requested changes
ざっと見た感じアイウエオ順が結構乱れてます。
手作業で直すのは簡単ですが、データからソートしてるはずですよね。
なんでこうなったんでしょう。

2021-01-24 10:39 UTC, KoheiB commented on etc/unitNames.txt
> +"ヴァイダ",
ヴではじまるユニット名の位置なんか総じて変じゃないですか？？

2021-01-24 10:39 UTC, KoheiB commented on etc/unitNames.txt
> +"ガウェイン",
あいうえお順が崩れている？

2021-01-25 05:23 UTC, henry11239987 commented
順序修正しました。

コード上で色々試してみたんですが、カタカナ漢字記号すべてをうまくソートするものがすぐに見つからず。。。
見たもの：https://note.kiriukun.com/entry/20181129-sort-with-local-compare

暫定処置ですが、Excel的なやつに貼り付けてソートしました。
内部的にソート必要となったら改めて考えましょう。。。

2021-01-25 12:15 UTC, merged