#42 add mixins
KoheiB/cipher_application pull request #49
Opened 2021-02-07 14:22 UTC by KoheiB

### やったこと

- [x] mixinsに以下を作成。

- Symbols.js
- GetImageUrl.js

- [x] mixins導入に関連するメソッドや変数名を修正

[WIP]データベース更新後、確認して問題がなければレビュー依頼します。

close #42

2021-02-11 09:33 UTC, KoheiB commented
@henry11239987 
レビューお願いします！

### やったこと
>  mixinsに以下を作成。
> 
> - Symbols.js
> 
> - GetImageUrl.js
> 
>  mixins導入に関連するメソッドや変数名を修正

- カードビューについては別Issueで実装するので、一旦すべてコメントアウト

2021-02-12 03:10 UTC, henry11239987 commented on pages/buildDeck.vue
> +import getSymbolColor from '../mixins/Symbols'
run dev時、下記のようなワーニングが出ています。

```
  267:25  warning  'C:\Users\kosuke\work\project\CipherApp_root\cipher_application\mixins\Symbols.js' imported multiple times  import/no-duplicates
  268:28  warning  'C:\Users\kosuke\work\project\CipherApp_root\cipher_application\mixins\Symbols.js' imported multiple times  import/no-duplicates
  269:32  warning  'C:\Users\kosuke\work\project\CipherApp_root\cipher_application\mixins\Symbols.js' imported multiple times  import/no-duplicates
```

同じファイル複数回インポートしてるぞ？といった旨のワーニングです。
動くことには動くのでこのままでも良いんですが、ワーニングが出る以上は上手いやり方ではないのかな、という印象を受けました。

下記点について、再検討いただけますか。
- 一度のインポートで、定数と共通メソッドを呼び出す方法があるのでは？
- 実はmixinsじゃなくてplugin側でinjectしたほうが良いのか？
    - 参考①：https://qiita.com/itouuuuuuuuu/items/bcad408842c7723e7ca3
    - 参考②：https://aloerina01.github.io/blog/2018-12-25-1

2021-02-12 04:04 UTC, henry11239987 commented on pages/buildDeck.vue
> +import getSymbolColor from '../mixins/Symbols'
追記：
L267, 268（およびL279,280）をコメントアウトしても、「getSymbolColor()」は動作するっぽいです。
参考②の記事にある通り、Mergeしているので「this,hoge()」のように呼び出せます。
（L267で指定している「symbolItems」を「mixins」に指定することで、「Symbols.js」のdataとmethodsがMergeされてthisから使えるのでは？）

このまま使うと、「this.getSymbolColor()」は使えるけども、「getSymbolColor()」ってどこに書いてあるねんって話になってしまいそうです。methodsに関してはplugin側でinjectしたほうが可読性が高い用に思います。

2021-02-12 04:20 UTC, henry11239987 commented on pages/buildDeck.vue
> +          ><v-icon class="pr-1">mdi-bookkeep-multiple</v-icon>Keep</v-tab
「mdi-bookkeep-multiple」だと画像が取得できていません。
もとの「mdi-bookmark-multiple」が正しいと思います。（おそらく一括変換で巻き込んだのかと）

2021-02-12 04:29 UTC, henry11239987 commented on pages/buildDeck.vue
> +              imageUrl: card.imageUrl,
モデル修正時に共有したとおり、imageUrlではなくrecordingが必要です。

2021-02-12 04:31 UTC, henry11239987 commented on pages/buildDeck.vue
> +            imageUrl: card.imageUrl,
同上

2021-02-12 04:32 UTC, henry11239987 commented on pages/buildDeck.vue
> +          imageUrl: this.getImageUrl(card),
同上

2021-02-12 04:40 UTC, henry11239987 requested changes
確認しました。いくつかコメントをしましたので確認及び修正をお願いします。
文面だけだと判断できないかもしれないので、会話が必要そうなら連絡ください。

また、コード外での指摘を1点記載しておきます。

・下記の通り、ユニット名周りが一部切れています。「×4」の高さに寄ってしまっている感じかと。
![image](https://user-images.githubusercontent.com/53003178/107730691-63355300-6d37-11eb-9210-562ba1ad8666.png)

2021-02-12 14:16 UTC, KoheiB commented
@henry11239987 
レビューありがとうございます。
WIPですが現時点までのレビューをお願いします。
本プルリクで #41 データ名のリファクタリングまで行い、マージすることとします。

---

### やったこと

#42 ご指摘いただいた部分

- methodsについてはinjectにより導入し、引数等を調整しました。

- constについてはメンターにベストプラクティスを聞いて、[こちら](https://konprogrammer.hatenablog.com/entry/2020/02/26/122607)の方法で導入しました。

> constantディレクトリなどに置いといて、importして使えばよいのでは？ byメンター

- mixinsは不要になったので削除しました。

<img width="377" alt="スクリーンショット 2021-02-12 19 09 25" src="https://user-images.githubusercontent.com/60537225/107755224-e077bc80-6d65-11eb-8da9-33fff24929eb.png">

- 僕の画面だと普通なんですけど、なんででしょう？Chromeですよね？

--- 

#40  #43  についても別ブランチで作業していたものを本ブランチにマージしたので、同様にレビューをお願いします。

- フィルター周りのメソッドをリファクタリング

- 出撃コストフィルターを追加（リファクタリングしたら簡単だったので追加しました。）

- カード検索ドロワーの高さをレスポンシブ対応

- フィルターをいじるとアサマバグが割と簡単に出るようになりました、一応解決の糸口は掴んでいるので、別Issueで対応します。

2021-02-13 05:35 UTC, henry11239987 commented on pages/buildDeck.vue
>            label="ユニット名で検索"
シンボルと出撃コストに合わせて、「ユニット名」だけにしましょう。
また、アイコンもなしで統一しましょう。

2021-02-13 05:39 UTC, henry11239987 commented on pages/buildDeck.vue
>        <!--▲ ユニット名フィルター ****************************************▲-->
画面上で見たとき、フィルター間で謎の空白行があるのですが意図的でしょうか？詰めてしまって良い気がします。
![image](https://user-images.githubusercontent.com/53003178/107842799-3cdfe800-6e09-11eb-91c8-27c04f3ad461.png)

2021-02-13 06:06 UTC, henry11239987 commented on pages/buildDeck.vue
>      // サーチ無限スクロール
L523の条件が9以下になってます。10未満に統一しましょう。
（Githubの仕様なのか、変更に関係なさそうな行にコメントつけられないっぽいのでここにつけてます）

2021-02-13 06:10 UTC, henry11239987 requested changes
確認しました。

コメントつけましたので確認をお願いします。

2021-02-13 06:16 UTC, KoheiB commented
@henry11239987 
指摘のあった点について修正しました！

- 環境ごとに異なるように見えた部分の表示を統一
- 検索ドロワーのフィルターの余白
- ユニット名フィルターのアイコン、ラベル
- メソッドの細かな修正

### その他やったこと

- 検索ドロワーの高さ再調整
- メソッド名、データ名、コンポーネント名のリファクタリング

よろしければマージお願いします！

2021-02-13 07:08 UTC, henry11239987 commented on pages/buildDeck.vue
> +          label="出撃"
「出撃」よりは「コスト」のほうがいい気がしました。
「CCコスト」は「CCコスト」って言うし、混同することはないのでは。

2021-02-13 07:35 UTC, henry11239987 approved these changes
確認しました。OKです。

2021-02-13 07:36 UTC, merged